---
# Copyright 2022, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create Terraform files based on scenario
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - vars/main.yml
    - defaults/main.yml
  tasks:
    - name: Generate Terraform files
      template:
        src: "{{ item.src }}"
        dest: "{{ playbook_dir }}/../terraform/{{ item.dest }}"
        mode: "0644"
      with_items:
        - { src: 'tf/000-variables.tf.j2', dest: '000-variables.tf' }
        - { src: 'tf/010-sshkey.tf.j2', dest: '010-sshkey.tf' }
        - { src: 'tf/020-network.tf.j2', dest: '020-network.tf' }
        - { src: 'tf/030-security_group.tf.j2', dest: '030-security_group.tf' }
        - { src: 'tf/040-flavor.tf.j2', dest: '040-flavor.tf' }
        - { src: 'tf/060-instance_controller.tf.j2', dest: '060-instance_controller.tf' }
        - { src: 'tf/061-instance_compute.tf.j2', dest: '061-instance_compute.tf' }
        - { src: 'tf/062-instance_loadbalancer.tf.j2', dest: '062-instance_loadbalancer.tf' }
        - { src: 'tf/063-instance_deployer.tf.j2', dest: '063-instance_deployer.tf' }
        - { src: 'tf/064-instance_ceph.tf.j2', dest: '064-instance_ceph.tf' }
        - { src: 'tf/100-inventory.tf.j2', dest: '100-inventory.tf' }
        - { src: 'tf/101-ansible-vars.tf.j2', dest: '101-ansible-vars.tf' }
        - { src: 'tf/105-private-key.tf.j2', dest: '105-private-key.tf' }
